theme: jekyll-theme-minimal
title: IPR Alumni Network
description: "This is the official site for the IPR Alumni Network, a platform for alumni to connect, share, and collaborate."
github: 
  project_page: true
